name: Binance Futures Actions

on: [push, pull_request]

jobs:
  Test_Binance_Futures_Bot:
    runs-on: ubuntu-latest

    container:
      image: mikaak/elixir-node:1.12-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Rebar & Hex
        run: mix local.hex --force && mix local.rebar --force
        working-directory: ./binance_futures_bot

      - name: Cache Deps & Build
        uses: actions/cache@v2
        with:
          key: ${{hashFiles('./binance_futures_bot/mix.lock')}}-deps-build-cache
          path: |
            ./binance_futures_bot/deps
            ./binance_futures_bot/_build
            !./binance_futures_bot/_build/dev/lib/binance_futures_bot/

      - name: Install Dependencies
        run: mix deps.get
        working-directory: ./binance_futures_bot

      - name: Compile Project
        run: mix compile
        working-directory: ./binance_futures_bot

      - name: Run Tests
        run: mix test
        working-directory: ./binance_futures_bot

